version: '3.8'
services:

  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    volumes:
      - ./hdfs/namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop-hive.env
    ports:
      - "9870:9870"
    networks:
      net_pet:
        ipv4_address: 172.27.1.10
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == zalman
          #- node.hostname == gordian77

  hive-server:
    image: bde2020/hive:2.3.2-postgresql-metastore
    container_name: hive-server
    env_file:
      - ./hadoop-hive.env
    environment:
      HIVE_CORE_CONF_javax_jdo_option_ConnectionURL: "jdbc:postgresql://hive-metastore/metastore"
      SERVICE_PRECONDITION: "hive-metastore:9083"
    ports:
      - "10000:10000"
    depends_on:
      - hive-metastore
    networks:
      net_pet:
        ipv4_address: 172.27.1.30
  
  hive-metastore:
    image: bde2020/hive:2.3.2-postgresql-metastore
    container_name: hive-metastore
    env_file:
      - ./hadoop-hive.env
    command: /opt/hive/bin/hive --service metastore
    environment:
      SERVICE_PRECONDITION: "namenode:9870 datanode:9864 hive-metastore-postgresql:5432"
    ports:
        - "9083:9083"
    depends_on:
      - hive-metastore-postgresql
    networks:
      net_pet:
        ipv4_address: 172.27.1.35
  
  hive-metastore-postgresql:
    image: bde2020/hive-metastore-postgresql:3.1.0
    container_name: hive-metastore-postgresql
    depends_on:
      - datanode
    networks:
      net_pet:
        ipv4_address: 172.27.1.40
    
  spark-master:
    image: bde2020/spark-master:3.1.1-hadoop3.2
    container_name: spark-master
    volumes:
      - ./hadoop_conf:/hadoop/conf
    ports:
      - 8080:8080
      - 7077:7077
    environment:
      - HADOOP_CONF_DIR=/hadoop/conf
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
    env_file:
      - ./hadoop-hive.env
    networks:
      net_pet:
        ipv4_address: 172.27.1.45
     
#  spark-worker-1:
  datanode:
    image: prubach/docker-spark-worker-hadoop-datanode:3.1.1-hadoop3.2
    container_name: datanode
    volumes:
      - ./hadoop_conf:/hadoop/conf
      - ./hdfs/datanode:/hadoop/dfs/data
      - ./bank:/bank
    depends_on:
      - spark-master
      - namenode
    env_file:
      - ./hadoop-hive.env
    environment:
      - SERVICE_PRECONDITION=namenode:9870
      - SPARK_MASTER=spark://spark-master:7077
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
      - HADOOP_CONF_DIR=/hadoop/conf
      - HIVE_CORE_CONF_javax_jdo_option_ConnectionURL=jdbc:postgresql://hive-metastore/metastore
    ports:
      - 8081:8081
      - 9864:9864
      - 50010:50010
    networks:
      net_pet:
        ipv4_address: 172.27.1.50
    deploy: 
      mode: replicated
      replicas: 1
      placement: 
        constraints: 
          - node.hostname == zalman
          #- node.hostname == gordian77

#  spark-worker-2:
  datanode-2:
    image: prubach/docker-spark-worker-hadoop-datanode:3.1.1-hadoop3.2
    #container_name: spark-worker-1
    container_name: datanode-2
    volumes:
      - ./hadoop_conf:/hadoop/conf
      - ./hdfs/datanode-2:/hadoop/dfs/data
      - ./bank:/bank
    depends_on:
      - spark-master
      - namenode
    env_file:
      - ./hadoop-hive.env
    environment:
      - SERVICE_PRECONDITION=namenode:9870
      - SPARK_MASTER=spark://spark-master:7077
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
      - HADOOP_CONF_DIR=/hadoop/conf
      - HIVE_CORE_CONF_javax_jdo_option_ConnectionURL=jdbc:postgresql://hive-metastore/metastore
    ports:
      - 8082:8081
      - 50076:9864
      - 50011:50010
    networks:
      net_pet:
        ipv4_address: 172.27.1.60
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == yoga7
          #- node.hostname == gordian76

#  datanode-3:
#    image: prubach/docker-spark-worker-hadoop-datanode:3.1.1-hadoop3.2
#    #image: bde2020/spark-worker:2.4.5-hadoop2.7
#    #container_name: spark-worker-1
#    container_name: datanode-3
#    volumes:
#      - ./hadoop_conf:/hadoop/conf
#      - ./hdfs/datanode-2:/hadoop/dfs/data
#      - ./bank:/bank
#    depends_on:
#      - spark-master
#      - namenode
#    env_file:
#      - ./hadoop-hive.env
#    environment:
#      - SERVICE_PRECONDITION=namenode:9870
#      - SPARK_MASTER=spark://spark-master:7077
#      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
#      - HADOOP_CONF_DIR=/hadoop/conf
#      - HIVE_CORE_CONF_javax_jdo_option_ConnectionURL=jdbc:postgresql://hive-metastore/metastore
#    ports:
#      - 8083:8081
#      - 50077:9864
#      - 50012:50010
#    networks:
#      net_pet:
#        ipv4_address: 172.27.1.65
#    deploy:
#      mode: replicated
#      replicas: 1
#      placement:
#        constraints:
#          #- node.hostname == yoga7
#          - node.hostname == gordian52

#  spark-worker-2:
#    image: bde2020/spark-worker:2.4.5-hadoop2.7
#    container_name: spark-worker-2
#    volumes:
#      - ./hadoop_conf:/hadoop/conf
#    depends_on:
#      - spark-master
#    environment:
#      - SPARK_MASTER=spark://spark-master:7077
#      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
#      - HADOOP_CONF_DIR=/hadoop/conf
#      - HIVE_CORE_CONF_javax_jdo_option_ConnectionURL=jdbc:postgresql://hive-metastore/metastore
#    ports:
#      - 8082:8081
#    env_file:
#      - ./hadoop-hive.env
#    networks:
#      net_pet:
#        ipv4_address: 172.27.1.60
#    deploy:
#      mode: replicated
#      replicas: 1
#      placement:
#        constraints:
#          #- node.hostname == yoga7
#          - node.hostname == gordian74

#    deploy:
#      mode: replicated
#      replicas: 2
#      update_config:
#        parallelism: 2

#  zeppelin:
#    #image: apache/zeppelin:0.9.0
#    image: prubach/docker-spark-zeppelin:0.9.0-spark3.1.1
#
##    hostname: zeppelin
#    container_name: zeppelin
#    environment:
#      CORE_CONF_fs_defaultFS: "hdfs://namenode:8020"
#      SPARK_MASTER: "spark://spark-master:7077"
#      MASTER: "spark://spark-master:7077"
#      SPARK_HOME: /spark
#      SPARK_MASTER_URL: spark://spark-master:7077
#      SPARK_SUBMIT_OPTIONS: "--packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.1.1,org.apache.kafka:kafka-clients:2.8.0"
#      HADOOP_CONF_DIR: /hadoop/conf
##      ZEPPELIN_ADDR: zeppelin
#      ZEPPELIN_INTERPRETER_DEP_MVNREPO: "https://repo.maven.apache.org/maven2"
#      ZEPPELIN_NOTEBOOK_PUBLIC: "false"
#      ZEPPELIN_ADDR: 0.0.0.0
#      ZEPPELIN_PORT: 19090
#      ZEPPELIN_JAVA_OPTS:
#        -Dspark.driver.memory=1g
#        -Dspark.executor.memory=2g
#        -Dzeppelin.spark.enableSupportedVersionCheck=false
#    ports:
#      - target: 19090
#        published: 19090
#        protocol: tcp
#        mode: ingress
#    env_file:
#      - ./hadoop-hive.env
#    volumes:
#      - ./zeppelin/conf/shiro.ini:/usr/lib/zeppelin/conf/shiro.ini
#      - ./hadoop_conf:/hadoop/conf
#      - ./zeppelin/data:/usr/lib/zeppelin/data:rw
#      - ./zeppelin/notebook:/usr/lib/zeppelin/notebook:rw
##    command: /usr/lib/zeppelin/bin/zeppelin.sh
#    networks:
#      net_pet:
#        ipv4_address: 172.27.1.70
#    deploy:
#      mode: replicated
#      replicas: 1
#      placement:
#        constraints:
#          #- node.hostname == gordian77
#          - node.hostname == zalman

## Official Zeppelin image - spark version incompatibility
#  zeppelin:
#    image: apache/zeppelin:0.9.0
#    container_name: zeppelin
#    environment:
#      ZEPPELIN_NOTEBOOK_DIR: '/notebook'
#    ports:
#      - 19090:8080
#    volumes:
#      - ./zeppelin/notebook:/notebook
#      - ./zeppelin/logs:/logs
#    networks:
#      net_pet:
#        ipv4_address: 172.27.1.71

  jupyter:
    image: jupyter/pyspark-notebook:python-3.8.8
    container_name: jupyter
    ports:
      - 19000:8888
    environment:
      SPARK_MASTER: spark://spark-master:7077
    volumes:
      - ./jupyter/work:/home/jovyan/work
    networks:
      net_pet:
        ipv4_address: 172.27.1.72


  hue:
      image: gethue/hue:20210510-140101
      hostname: hue
      container_name: hue
      dns: 8.8.8.8
      ports:
      - "8888:8888"
      volumes:
        - ./hue-overrides.ini:/usr/share/hue/desktop/conf/z-hue.ini
      depends_on:
      - "database"
      networks:
        net_pet:
          ipv4_address: 172.27.1.75
  
  database:
      image: mysql:5.7
      container_name: database
      ports:
          - "33061:3306"
      command: --init-file /data/application/init.sql
      volumes:
          - ./mysql/data:/var/lib/mysql
          - ./init.sql:/data/application/init.sql
      environment:
          MYSQL_ROOT_USER: root
          MYSQL_ROOT_PASSWORD: secret
          MYSQL_DATABASE: hue
          MYSQL_USER: hue
          MYSQL_PASSWORD: secret
      networks:
        net_pet:
          ipv4_address: 172.27.1.80
      deploy:
        mode: replicated
        replicas: 1
        placement:
          constraints:
            - node.hostname == zalman
            #- node.hostname == gordian77
  zookeeper:
    image: zookeeper:3.7.0
    ports:
      - "2181:2181"
    networks:
      net_pet:
        ipv4_address: 172.27.1.90

  kafka:
    #image: wurstmeister/kafka:2.13-2.7.0
    image: bitnami/kafka:2.8.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://172.27.1.100:9092
      KAFKA_ADVERTISED_HOST_NAME: 172.27.1.100
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      #KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      net_pet:
        ipv4_address: 172.27.1.100

#  streamsets:
#    image: streamsets/datacollector:3.17.0-latest
#    ports:
#      - "18630:18630"
#    networks:
#      net_pet:
#        ipv4_address: 172.27.1.17  

networks:
  net_pet:
    ipam:
      driver: default
      config:
        - subnet: 172.27.1.0/24
